# Generated by Django 6.0.4 on 2026-04-16 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='item code')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Arabic name')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='English name')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='image')),
                ('pieces_per_package', models.PositiveIntegerField(default=1, verbose_name='pieces per package')),
                ('packages_per_carton', models.PositiveIntegerField(default=1, verbose_name='packages per carton')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='wholesale price')),
                ('qty_building_warehouse', models.IntegerField(default=0, verbose_name='qty — building warehouse')),
                ('qty_sea_warehouse', models.IntegerField(default=0, verbose_name='qty — sea warehouse')),
                ('qty_shop', models.IntegerField(default=0, verbose_name='qty — shop')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='category')),
                ('tags', models.ManyToManyField(blank=True, to='catalog.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['item_code'],
            },
        ),
    ]
